export const SELECTED_CURRENCY = 'SELECTED_CURRENCY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';



