export const SELECTED_CURRENCY = 'SELECTED_CURRENCY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_COUNTER_BY_POSITION = 'INCREMENT_COUNTER_BY_POSITION';
export const DECREMENT_COUNTER_BY_POSITION = 'DECREMENT_COUNTER_BY_POSITION';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';



